controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_homepage:
    path: /{_locale}
    controller: App\Controller\HomepageController::index
    requirements:
        _locale: en|es  # Supported languages
